### ISSUE TITLE
copy polymorphic model instance

### ISSUE THREAD

**Issue by kingel** [jazzband/django-polymorphic#56]
I try to copy a polymorphic model instance, with normal objects I'd di

ob.pk = None
ob.save()

but this doesn't work for a polymorphic instance, I end up with some kind of unbound entry. Is there any documentation on how to do this? Or any pointers?

**Comment by mscuthbert** [comment]
Thanks for the pointer in the right direction -- in case anyone sees this later, here's what I did:

```
o = MyPolymorphicSubTable.objects.first()
o.id  # 22
o.pk # 22
o.id = None
o.pk = None # both need to be set
o.save()
o.id # 434
o.pk # 434
```
