### ISSUE TITLE
Release to PyPI

### ISSUE THREAD

**Issue by martin-thoma** [jazzband/django-polymorphic#610]
I've just noticed that there are several changes in master which are not on PyPI.
The last release was in 2021: https://pypi.org/project/django-polymorphic/

What is blocking a new release?

**Comment by akx** [comment]
Please see https://github.com/jazzband/django-polymorphic/issues/598#issuecomment-2151340825 :)

**Comment by martin-thoma** [comment]
Oh, nice! As this is implicitly covered by that other issue and I don't want to cause unnecessary noise, I'll close this one.

https://github.com/pypi/support/issues/4164 is the interesting part to follow :-)
